#! /bin/bash

SUPPORTED_PACKAGE_MANAGERS=
_INSTALL_BIN="$HOME/.local/bin"

package_manager="$(sh <(curl -s https://raw.githubusercontent.com/erichdongubler-dotfiles/base/master/.local/bin/detect-package-manager))"
if [ $? -ne 0 ]; then
	exit 1
fi
eval "$package_manager git curl"
if [ $? -ne 0 ]; then
	exit 1
fi

mkdir -p "$_INSTALL_BIN"
pushd "$_INSTALL_BIN" > /dev/null
export PATH="$PATH:$_INSTALL_BIN" && curl -O "https://raw.githubusercontent.com/RichiH/vcsh/master/vcsh" && chmod +x "$_INSTALL_BIN/vcsh"
if [ $? -ne 0 ]; then
	popd > /dev/null
	exit 1
fi
popd > /dev/null

for package in base "$@"; do
	vcsh clone git@github.com:erichdongubler-dotfiles/"$package".git
done

echo "Done! If you're in bash, the run \`. ~/.bash_profile\`."
